### ISSUE TITLE
Trying to cross compile on Mac to Windows, errors:

### ISSUE THREAD

**Issue by treeform** [goxjs/gl#22]
bash-3.2$ GOOS=windows GOARCH=386 go build -o g4.exe g4.go
../github.com/goxjs/gl/gl_opengl.go:10:2: no buildable Go source files in /p/lorgenome/src/github.com/go-gl/gl/v2.1/gl
../github.com/goxjs/glfw/desktop.go:10:2: no buildable Go source files in /p/lorgenome/src/github.com/go-gl/glfw/v3.2/glfw

Has any one tried to cross compile this?

**Comment by dmitshur** [comment]
Cross-compiling packages that use cgo (which is both gl and glfw) is quite difficult (because you need a C compiler that is able to cross-compile as well). I've never done it before.

Unless you're able to find a solution, I would suggest building it on the target platform directly (i.e., if you want a Windows binary, build it on Windows).
